### ISSUE TITLE
MaxiMask does not work with TensorFlow v2.20.0

### ISSUE THREAD

**Issue by ebertin** [mpaillassa/MaxiMask#33]
Hi Maxime 👋
MaxiMask does not seem to work with the latest version of TensorFlow (and Python 3.13). One gets the following error message:
```
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

Detected at node Sigmoid defined at (most recent call last):
<stack traces unavailable>
JIT compilation failed.
	 [[{{node Sigmoid}}]] [Op:__inference_restored_function_body_15726]
```

No problem with TensorFlow v2.16.1 (and Python 3.12).
Cheers
